apiVersion: batch/v1
kind: CronJob
metadata:
  name: maie-daily
spec:
  schedule: "15 22 * * MON-FRI"  # 10:15pm UTC weekdays
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: runner
              image: ghcr.io/yourorg/yourrepo/maie-api:latest
              command: ["bash","-lc","make bt-constrained && make report-html"]
              env:
                - { name: LOG_LEVEL, value: "INFO" }
              volumeMounts:
                - { name: expected, mountPath: /app/expected }
                - { name: outputs,  mountPath: /app/outputs_from_expected }
          volumes:
            - name: expected
              persistentVolumeClaim: { claimName: expected-pvc }
            - name: outputs
              persistentVolumeClaim: { claimName: outputs-pvc }
