name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install system deps
        run: |
          brew update
          brew install libomp cmake openblas pkg-config
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip wheel setuptools
          pip install -e .[dev]
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check .
          ruff format --check .
          mypy src
      - name: Test
        run: |
          . .venv/bin/activate
          pytest -q


